### PR TITLE
Updated filter command based on git-scm.com example

### PR DESCRIPTION
**Pull request by gdressel**
Since git-rewrite-author didn't work for me (command did not rewrite any commit in my repos) I prolonged my web recherche on git author rewriting.
Eventually I stumbled over some official example about how to rewrite authors - this example was a little bit different to what I've found before on the web (of which all seem to be based on https://help.github.com/articles/changing-author-info/).

See https://git-scm.com/docs/git-filter-branch#_examples / Section --env-filter

That slightly different variant of history rewriting did the job for me on my repository.
It might help others too -- so here's the pull request.

### CODE REVIEW

**Comment by gdressel** [comment]
BTW: running on git version 2.19.1 here.

**Comment by crazy-max** [comment]
@guedressel Ok thanks I will take a look on this. Do you have an example of git repo and authors.json file for me ?

**Comment by gdressel** [comment]
@crazy-max I was working on a private repos. I've two ideas why the current version didn't work: There were "+" signs in the mail address; my git version is quite recent - maybe something changed in git from older versions.

**Comment by crazy-max** [comment]
These changes are now available since version 1.3.0

**Pull request closed without merging**
